// <auto-generated />
using System;
using HospitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalManagement.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260620171822_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HospitalManagement.Models.Admission", b =>
                {
                    b.Property<int>("AdmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdmissionId"));

                    b.Property<DateTime?>("ActualDischargeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("AdmissionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AdmissionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("BedId")
                        .HasColumnType("int");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("DischargeNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpectedDischargeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("AdmissionId");

                    b.HasIndex("BedId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("WardId");

                    b.ToTable("Admissions");
                });

            modelBuilder.Entity("HospitalManagement.Models.Bed", b =>
                {
                    b.Property<int>("BedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BedId"));

                    b.Property<string>("BedNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("BedId");

                    b.HasIndex("WardId");

                    b.ToTable("Beds");

                    b.HasData(
                        new
                        {
                            BedId = 1,
                            BedNumber = "G-01",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 2,
                            BedNumber = "G-02",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 3,
                            BedNumber = "G-03",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 4,
                            BedNumber = "G-04",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 5,
                            BedNumber = "G-05",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 6,
                            BedNumber = "G-06",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 7,
                            BedNumber = "G-07",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 8,
                            BedNumber = "G-08",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 9,
                            BedNumber = "G-09",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 10,
                            BedNumber = "G-10",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 11,
                            BedNumber = "G-11",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 12,
                            BedNumber = "G-12",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 13,
                            BedNumber = "G-13",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 14,
                            BedNumber = "G-14",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 15,
                            BedNumber = "G-15",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 16,
                            BedNumber = "G-16",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 17,
                            BedNumber = "G-17",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 18,
                            BedNumber = "G-18",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 19,
                            BedNumber = "G-19",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 20,
                            BedNumber = "G-20",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 21,
                            BedNumber = "G-21",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 22,
                            BedNumber = "G-22",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 23,
                            BedNumber = "G-23",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 24,
                            BedNumber = "G-24",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 25,
                            BedNumber = "G-25",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 26,
                            BedNumber = "G-26",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 27,
                            BedNumber = "G-27",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 28,
                            BedNumber = "G-28",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 29,
                            BedNumber = "G-29",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 30,
                            BedNumber = "G-30",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 1
                        },
                        new
                        {
                            BedId = 31,
                            BedNumber = "ICU-01",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 32,
                            BedNumber = "ICU-02",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 33,
                            BedNumber = "ICU-03",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 34,
                            BedNumber = "ICU-04",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 35,
                            BedNumber = "ICU-05",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 36,
                            BedNumber = "ICU-06",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 37,
                            BedNumber = "ICU-07",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 38,
                            BedNumber = "ICU-08",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 39,
                            BedNumber = "ICU-09",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 40,
                            BedNumber = "ICU-10",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 41,
                            BedNumber = "ICU-11",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 42,
                            BedNumber = "ICU-12",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 43,
                            BedNumber = "ICU-13",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 44,
                            BedNumber = "ICU-14",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 45,
                            BedNumber = "ICU-15",
                            BedType = "ICU",
                            IsOccupied = false,
                            WardId = 2
                        },
                        new
                        {
                            BedId = 46,
                            BedNumber = "M-01",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 47,
                            BedNumber = "M-02",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 48,
                            BedNumber = "M-03",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 49,
                            BedNumber = "M-04",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 50,
                            BedNumber = "M-05",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 51,
                            BedNumber = "M-06",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 52,
                            BedNumber = "M-07",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 53,
                            BedNumber = "M-08",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 54,
                            BedNumber = "M-09",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 55,
                            BedNumber = "M-10",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 56,
                            BedNumber = "M-11",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 57,
                            BedNumber = "M-12",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 58,
                            BedNumber = "M-13",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 59,
                            BedNumber = "M-14",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 60,
                            BedNumber = "M-15",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 61,
                            BedNumber = "M-16",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 62,
                            BedNumber = "M-17",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 63,
                            BedNumber = "M-18",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 64,
                            BedNumber = "M-19",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 65,
                            BedNumber = "M-20",
                            BedType = "Standard",
                            IsOccupied = false,
                            WardId = 3
                        },
                        new
                        {
                            BedId = 66,
                            BedNumber = "P-01",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 67,
                            BedNumber = "P-02",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 68,
                            BedNumber = "P-03",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 69,
                            BedNumber = "P-04",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 70,
                            BedNumber = "P-05",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 71,
                            BedNumber = "P-06",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 72,
                            BedNumber = "P-07",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 73,
                            BedNumber = "P-08",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 74,
                            BedNumber = "P-09",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 75,
                            BedNumber = "P-10",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 76,
                            BedNumber = "P-11",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 77,
                            BedNumber = "P-12",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 78,
                            BedNumber = "P-13",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 79,
                            BedNumber = "P-14",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 80,
                            BedNumber = "P-15",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 81,
                            BedNumber = "P-16",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 82,
                            BedNumber = "P-17",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 83,
                            BedNumber = "P-18",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 84,
                            BedNumber = "P-19",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 85,
                            BedNumber = "P-20",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 86,
                            BedNumber = "P-21",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 87,
                            BedNumber = "P-22",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 88,
                            BedNumber = "P-23",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 89,
                            BedNumber = "P-24",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        },
                        new
                        {
                            BedId = 90,
                            BedNumber = "P-25",
                            BedType = "Pediatric",
                            IsOccupied = false,
                            WardId = 4
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("ConsultationSchedule")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("OnDuty")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("WardId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            ConsultationSchedule = "Mon-Fri 9AM-5PM",
                            Email = "ahmed.khan@medicore.pk",
                            FullName = "Dr. Ahmed Khan",
                            IsAvailable = true,
                            JoinedDate = new DateTime(2015, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = true,
                            PhoneNumber = "0321-1234567",
                            Specialization = "General Medicine",
                            WardId = 1,
                            YearsExperience = 12
                        },
                        new
                        {
                            DoctorId = 2,
                            ConsultationSchedule = "Mon-Sat 8AM-4PM",
                            Email = "sara.ali@medicore.pk",
                            FullName = "Dr. Sara Ali",
                            IsAvailable = true,
                            JoinedDate = new DateTime(2012, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = true,
                            PhoneNumber = "0322-2345678",
                            Specialization = "Cardiology",
                            WardId = 2,
                            YearsExperience = 15
                        },
                        new
                        {
                            DoctorId = 3,
                            ConsultationSchedule = "Tue-Sat 10AM-6PM",
                            Email = "fatima.raza@medicore.pk",
                            FullName = "Dr. Fatima Raza",
                            IsAvailable = true,
                            JoinedDate = new DateTime(2016, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = false,
                            PhoneNumber = "0323-3456789",
                            Specialization = "Obstetrics & Gynecology",
                            WardId = 3,
                            YearsExperience = 10
                        },
                        new
                        {
                            DoctorId = 4,
                            ConsultationSchedule = "Mon-Thu 9AM-3PM",
                            Email = "usman.sheikh@medicore.pk",
                            FullName = "Dr. Usman Sheikh",
                            IsAvailable = false,
                            JoinedDate = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = false,
                            PhoneNumber = "0324-4567890",
                            Specialization = "Pediatrics",
                            WardId = 4,
                            YearsExperience = 8
                        },
                        new
                        {
                            DoctorId = 5,
                            ConsultationSchedule = "Mon-Fri 11AM-7PM",
                            Email = "zara.hussain@medicore.pk",
                            FullName = "Dr. Zara Hussain",
                            IsAvailable = true,
                            JoinedDate = new DateTime(2010, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = true,
                            PhoneNumber = "0325-5678901",
                            Specialization = "Neurology",
                            WardId = 1,
                            YearsExperience = 18
                        },
                        new
                        {
                            DoctorId = 6,
                            ConsultationSchedule = "Wed-Sun 8AM-2PM",
                            Email = "bilal.malik@medicore.pk",
                            FullName = "Dr. Bilal Malik",
                            IsAvailable = true,
                            JoinedDate = new DateTime(2013, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = false,
                            PhoneNumber = "0326-6789012",
                            Specialization = "Orthopedics",
                            WardId = 1,
                            YearsExperience = 14
                        },
                        new
                        {
                            DoctorId = 7,
                            ConsultationSchedule = "Mon-Fri 7AM-3PM",
                            Email = "hina.baig@medicore.pk",
                            FullName = "Dr. Hina Baig",
                            IsAvailable = true,
                            JoinedDate = new DateTime(2017, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = true,
                            PhoneNumber = "0327-7890123",
                            Specialization = "Internal Medicine",
                            WardId = 2,
                            YearsExperience = 9
                        },
                        new
                        {
                            DoctorId = 8,
                            ConsultationSchedule = "Tue-Sat 12PM-8PM",
                            Email = "kamran.iqbal@medicore.pk",
                            FullName = "Dr. Kamran Iqbal",
                            IsAvailable = false,
                            JoinedDate = new DateTime(2019, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OnDuty = true,
                            PhoneNumber = "0328-8901234",
                            Specialization = "Dermatology",
                            WardId = 4,
                            YearsExperience = 7
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("KnownAllergies")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "House 12, Block A, Gulshan-e-Iqbal, Karachi",
                            BloodGroup = "B+",
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "asif@gmail.com",
                            EmergencyContactName = "Ayesha Asif",
                            EmergencyContactPhone = "0301-9998887",
                            FullName = "Mohammad Asif",
                            Gender = "Male",
                            KnownAllergies = "Penicillin",
                            MedicalHistory = "Hypertension, Diabetes Type 2",
                            PhoneNumber = "0301-1112223",
                            RegistrationDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 2,
                            Address = "Flat 5, Tower B, DHA Phase 6, Karachi",
                            BloodGroup = "O+",
                            DateOfBirth = new DateTime(1995, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContactName = "Tariq Farrukh",
                            EmergencyContactPhone = "0302-6667778",
                            FullName = "Nadia Farrukh",
                            Gender = "Female",
                            KnownAllergies = "None",
                            MedicalHistory = "Asthma",
                            PhoneNumber = "0302-2223334",
                            RegistrationDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 3,
                            Address = "Plot 8, Street 3, North Nazimabad, Karachi",
                            BloodGroup = "A-",
                            DateOfBirth = new DateTime(1965, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContactName = "Sana Qureshi",
                            EmergencyContactPhone = "0303-4445556",
                            FullName = "Rizwan Qureshi",
                            Gender = "Male",
                            KnownAllergies = "Sulfa drugs",
                            MedicalHistory = "Cardiac arrhythmia, Hypertension",
                            PhoneNumber = "0303-3334445",
                            RegistrationDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 4,
                            Address = "House 45, Bahadurabad, Karachi",
                            BloodGroup = "AB+",
                            DateOfBirth = new DateTime(1990, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContactName = "Omar Siddiqui",
                            EmergencyContactPhone = "0304-1112223",
                            FullName = "Amna Siddiqui",
                            Gender = "Female",
                            PhoneNumber = "0304-4445556",
                            RegistrationDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 5,
                            Address = "Flat 2, Model Colony, Karachi",
                            BloodGroup = "O-",
                            DateOfBirth = new DateTime(2018, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContactName = "Hassan Ali",
                            EmergencyContactPhone = "0305-7778889",
                            FullName = "Ali Hassan",
                            Gender = "Male",
                            MedicalHistory = "Recurrent fever episodes",
                            PhoneNumber = "0305-5556667",
                            RegistrationDate = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PatientId = 6,
                            Address = "House 78, Gulberg Town, Karachi",
                            BloodGroup = "A+",
                            DateOfBirth = new DateTime(1985, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyContactName = "Imran Nawaz",
                            EmergencyContactPhone = "0306-2223334",
                            FullName = "Sobia Nawaz",
                            Gender = "Female",
                            MedicalHistory = "Pregnancy - 32 weeks",
                            PhoneNumber = "0306-6667778",
                            RegistrationDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Treatment", b =>
                {
                    b.Property<int>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TreatmentId"));

                    b.Property<int>("AdmissionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("Medication")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TreatmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TreatmentId");

                    b.HasIndex("AdmissionId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("HospitalManagement.Models.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WardId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("TotalBeds")
                        .HasColumnType("int");

                    b.Property<string>("WardType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("WardId");

                    b.ToTable("Wards");

                    b.HasData(
                        new
                        {
                            WardId = 1,
                            Description = "General patient care ward for routine treatments",
                            Name = "General Ward",
                            TotalBeds = 30,
                            WardType = "General"
                        },
                        new
                        {
                            WardId = 2,
                            Description = "Critical care unit for life-threatening conditions",
                            Name = "Intensive Care Unit",
                            TotalBeds = 15,
                            WardType = "ICU"
                        },
                        new
                        {
                            WardId = 3,
                            Description = "Dedicated ward for maternity and newborn care",
                            Name = "Maternity Ward",
                            TotalBeds = 20,
                            WardType = "Maternity"
                        },
                        new
                        {
                            WardId = 4,
                            Description = "Specialized care for children and infants",
                            Name = "Pediatric Ward",
                            TotalBeds = 25,
                            WardType = "Pediatric"
                        });
                });

            modelBuilder.Entity("HospitalManagement.Models.Admission", b =>
                {
                    b.HasOne("HospitalManagement.Models.Bed", "Bed")
                        .WithMany("Admissions")
                        .HasForeignKey("BedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Doctor", "Doctor")
                        .WithMany("Admissions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Patient", "Patient")
                        .WithMany("Admissions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Ward", "Ward")
                        .WithMany("Admissions")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bed");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalManagement.Models.Bed", b =>
                {
                    b.HasOne("HospitalManagement.Models.Ward", "Ward")
                        .WithMany("Beds")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalManagement.Models.Doctor", b =>
                {
                    b.HasOne("HospitalManagement.Models.Ward", "Ward")
                        .WithMany("Doctors")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("HospitalManagement.Models.Treatment", b =>
                {
                    b.HasOne("HospitalManagement.Models.Admission", "Admission")
                        .WithMany("Treatments")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalManagement.Models.Doctor", "Doctor")
                        .WithMany("Treatments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("HospitalManagement.Models.Admission", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("HospitalManagement.Models.Bed", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("HospitalManagement.Models.Doctor", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("HospitalManagement.Models.Patient", b =>
                {
                    b.Navigation("Admissions");
                });

            modelBuilder.Entity("HospitalManagement.Models.Ward", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("Beds");

                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
